### ISSUE TITLE
Graphs not working

### ISSUE THREAD

**Issue by Worren** [opensemanticsearch/open-semantic-desktop-search#12]
On my  Open search VM the graph page is not working (Graphs are not shown). Do I need to install some additional Packages?

**Comment by opensemanticsearch** [comment]
The current graph view shows only co-occurences (connection if both occur in a document or stronger connection both if many documents) of named entities like persons, organizations, places or concepts.

Therefore you have to define such named entities i.e. by an entry to the [thesaurus](http://www.opensemanticsearch.org/doc/datamanagement/thesaurus) or in external [lists, dictionary or ontologies](http://www.opensemanticsearch.org/doc/datamanagement/ontologies).

If that doesn't work but computer has much load:

If there are too many connected results and to few RAM that might not work, since the graph view is parameterized on an former investigative research. More flexible graph view parameters/UIs maybe will follow next year, if there is no better Open Source alternate that could be integrated.
