### ISSUE TITLE
OSX 10.10.5 / German Open Sematic Desktop Version

### ISSUE THREAD

**Issue by medienverbinder** [opensemanticsearch/open-semantic-desktop-search#2]
The OSX 10.10.5 archiver tool generates a "cpgz" File while extracting open-semantic-desktop-search-de_15.07.03.zip. In order to fix the problem you can use ditto.

Open CLI and type in:

ditto -x -k open-semantic-desktop-search-de_15.07.03.zip OpenSemanticDesktopSearch

In the directory "OpenSemanticDesktopSearch" the VDI file will be created.

**Comment by opensemanticsearch** [comment]
Since the virtual machine now is available in appliance format OVA (so you don't have to configure some settings manually) instead of only the virtual disc image VDI, you don't have to unzip it manually anymore (which could cause problems with older versions of tools for unzipping i.e. because of the file size > 2 GB).
