### ISSUE TITLE
Build questions

### ISSUE THREAD

**Issue by Quyrean** [opensemanticsearch/open-semantic-desktop-search#22]
Hi,

I would like to contribute and am trying to build this but having no luck.  Are there any automated build scripts or more documentation on how to build?  I tried the readme, but I get a vm with no opensemantic search installed it and it does not shutdown as stated in the readme.

from readme:
> Copy semantic search debian package to the path src/packages.chroot
> Run the build script.
> Add an Virtual Box setup for the VM image
> ...
> Run this VM so installation within VM environment starts
> After installation the VM will shutdown.

user@dev1:~/repos/opensemanticsearch/open-semantic-desktop-search$ cp ../open-semantic-search/build/open-semantic-*.deb src/packages.chroot/

user@dev1:~/repos/opensemanticsearch/open-semantic-desktop-search$ ls -l src/packages.chroot/
total 422884

-rw-r--r-- 1 user user     39758 May  3 19:25 open-semantic-etl_18.05.01.deb
-rw-r--r-- 1 user user     39762 May  3 19:25 open-semantic-etl_18.05.02.deb
-rw-r--r-- 1 user user     39766 May  3 19:25 open-semantic-etl-elasticsearch_18.05.01.deb
-rw-r--r-- 1 user user     39762 May  3 19:25 open-semantic-etl-elasticsearch_18.05.02.deb
-rw-r--r-- 1 user user   2081174 May  3 19:25 open-semantic-search_18.05.01.deb
-rw-r--r-- 1 user user 430406440 May  3 19:26 open-semantic-search_18.05.02.deb
-rw-r--r-- 1 user user    182630 May  3 19:26 open-semantic-search-apps_18.05.01.deb
-rw-r--r-- 1 user user    182594 May  3 19:26 open-semantic-search-apps_18.05.02.deb
-rwxr-xr-x 1 user user      1630 May  1 21:46 opensemanticsearch-connector-files-nautilus-plugin_15.06.26_all.deb

user@dev1:~/repos/opensemanticsearch/open-semantic-desktop-search$ sudo ./build

Then I created a new linux vm in virtual box.  I ran it and it installed several things, but none of the open semantic search binaries.  Here is a ss of my vm running.

![image](https://user-images.githubusercontent.com/30613311/39601613-214a53e8-4ee8-11e8-9d66-ab6c378afdab.png)

Any help would be appreciated.  Thanks

**Comment by opensemanticsearch** [comment]
You have only to add the current open-semantic-search_xx.xx.xx.deb to the directory.

Bit its worth to wait, since major architecture changes and upgrades of all components to Solr 7 and the new Open Semantic Entity Search API will come tomorrow / next days.

After that i'll add better / additional documentation and build scripts which can build all modules from scratch/git after major release next days.

I let this issue open until new infos online.

**Comment by Quyrean** [comment]
Thank you for the update.  Please let me know if I can help test or anything.  Is there a message board or developer group/email list in English I can subscribe to or is it mostly in German?

thanks!

**Comment by opensemanticsearch** [comment]
The new beta server Debian package and english desktop search VM should be available for download now, if you like to test (maybe yet problems, since major upgrades and architecture changes, but which will be a more stable base in mid and long term).

You can use github issues (public) or write email to me at info@opensemanticsearch.org

**Comment by opensemanticsearch** [comment]
I extended the readme.

The package this repository is dependent on is the download of open semantic search server all in one package from https://opensemanticsearch.org/download or git repository open-semantic-search (the last has dependencies to the other git repositories)

Please reopen or write email, if more questions.
