### ISSUE TITLE
blacklist-url-suffix is not working

### ISSUE THREAD

**Issue by miniminime** [opensemanticsearch/open-semantic-desktop-search#4]
Hi,
This seems not to work. Used per line one suffix in the form of ".css" (without quotes).

**Comment by miniminime** [comment]
Also in the newest version (open-semantic-desktop-search_16.02.09.zip) it's not working.

**Comment by opensemanticsearch** [comment]
I tried this and it works with version 16.02.09 (the blacklist filter plugin got some bugfixes).

Maybe your config entry is considered as comment, which can be used to describe/comment blacklist entries.

Iis there is a # in front of the blacklist entry?

For example the .css entry is commented out in the delivered example blacklist files. If not edited yet, just delete the # in front of the line ...

Another possibility, why the filter might not work:

Is the Suffix of the files .CSS and not .css ? So you have to add .CSS because the list is case sensitive.

**Comment by miniminime** [comment]
I'm sure it must be me, but:
```
# Blacklist of URL Suffixes like file endings
.png .gif .css .jpg .eot .svg .ttf
```
<a href='http://postimage.org/' target='_blank'><img src='http://s7.postimg.org/s4j4rfcmj/Capture.png' border='0' alt="Capture" /></a><br /><a target='_blank' href='http://postimage.org/index.php?lang=german'>fotos kostenlos</a><br /><br />

**Comment by opensemanticsearch** [comment]
Ah ok, the problem is, that all suffixes are defined in one single line.

You have to config only one URL/suffix/prefix per line.

Change

.png .gif .css .jpg .eot .svg .ttf

to

.png
.gif
.css
.jpg
.eot
.svg
.ttf

and maybe add .CSS and so on, if some file suffixes are upper case.

Maybe its a sign to build an UI for that ;)

**Comment by miniminime** [comment]
Thank you, now it works flawlessly.
