### ISSUE TITLE
Do automatic textrecognition (OCR) for images later and in background

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#9]
Do automatic textrecognition (OCR) for (embedded) images (many analysis time for few additional text) later and in brackground, so most other data/documents or most parts of the documents will be searchable many times faster.

**Comment by Mandalka** [comment]
OCR of images embedded in PDF files is done by own plugin, so enrich with that plugin later is no problem.

But since Tika is doing OCR for other image files out of the box, if Tesseract is installed:

To check: Can Tika server be called without installed Tesseract OCR, switched off only by parameter without changing Tika config or without setup an own Tika server instance (would need additional RAM) for that?

**Comment by Mandalka** [comment]
Tika OCR can be switched off by hack / set option Tesseract binary to /bin/false ...

**Comment by Mandalka** [comment]
Related discussion in Tika project: Discussion to future PDF OCR: https://issues.apache.org/jira/browse/TIKA-2749

**Comment by Mandalka** [comment]
This will be implemented as option in next Open Semantic ETL / Open Semantic Search release by https://github.com/opensemanticsearch/open-semantic-search/issues/178, so automatically will be part of Open Semantic Desktop Search, too.
